apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-demo
spec:
  selector:
    matchLabels:
      app: aks-demo
  template:
    metadata:
      labels:
        app: aks-demo
    spec: 
      containers:
      - name: aks-demo
        image: amitd.azurecr.io/myapp
        resources:
          limits: 
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
