name: Build Push Docker Image

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v1
      with:
        login-server: amitd.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t amitd.azurecr.io/myapp:${{ github.sha }}
        docker push amitd.azurecr.io/myapp:${{ github.sha }}
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
